[hosts]
node1 ansible_host=192.168.1.84 ansible_user=aguir-chams ansible_python_interpreter=/usr/bin/python3
node2 ansible_host=192.168.1.28 ansible_user=aguir-chams ansible_python_interpreter=/usr/bin/python3

